# class 13-11-2024

## Numpy arrays

In [6]:
import numpy as np

In [7]:
arr = np.array([1, 2, 3], dtype=np.float64)
print(arr)
print("Data type:", arr.dtype)

[1. 2. 3.]
Data type: float64


In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [12]:
arr = np.array([10, 20, 30, 40, 50])

#Access elements by index



print("First Element:", arr[0])
print("Last Element:", arr[-1])
#slicing
print("First Three Elements:", arr[:3])
print("Elements from Index 2 to 4:", arr[2:5])

First Element: 10
Last Element: 50
First Three Elements: [10 20 30]
Elements from Index 2 to 4: [30 40 50]


In [13]:
arr = np.array([1, 2, 3])
print("Array + 10:", arr + 10)

Array + 10: [11 12 13]


In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

print("Broadcasted Addition:\n", a + b)

Broadcasted Addition:
 [[11 22 33]
 [14 25 36]]


In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

#Element-wise multiplication



print("Element-wise Multiplication:\n", A * B)

#Matrix multiplication (dot product)



print("Matrix Multiplication:\n", np.dot(A, B))

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [16]:
A = np.array([[1, 2], [3, 4]])
print("Original Matrix:\n", A)
print("Transpose:\n", A.T)

Original Matrix:
 [[1 2]
 [3 4]]
Transpose:
 [[1 3]
 [2 4]]


In [17]:
from numpy.linalg import inv

A = np.array([[1, 2], [3, 4]])
print("Inverse:\n", inv(A))

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [18]:
np.array([1, 2, 3])

array([1, 2, 3])

In [19]:
np.zeros((3, 4))  # 3x4 matrix of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((2, 3))  # 2x3 matrix of ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.eye(3)  # 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]

array([0, 2, 4, 6, 8])

In [23]:
np.linspace(0, 1, 5)  # [0.  0.25 0.5  0.75 1. ]

array([0.  , 0.25, 0.5 , 0.75, 1.  ])